### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by HaecheonLee** [HaecheonLee/maze#2]
* [x] Visualize the array of a created maze, using the numbers of each sqaure indicating
* [ ] Add a feature that an user can select a starting point and an ending point on squares of the grid in the screen
* [ ] Provide bfs and dfs algorithms to escape from the starting point to ending point. As well, work on the visualizing moving point/whatever on the grid,

**Comment by HaecheonLee** [comment]
* [] Check the algorithm that creates the maze
![dfsfkfksdjfds](https://user-images.githubusercontent.com/16802605/140855311-7cc6ffc7-a32d-46b7-a2b5-96eafaa7d9e8.PNG)

**Comment by HaecheonLee** [comment]
Updated maze
![dfsfkfksdjfds](https://user-images.githubusercontent.com/16802605/140991755-ff5cb74d-ba05-4a0e-aef2-713b9bffd911.PNG)

**Comment by HaecheonLee** [comment]
https://user-images.githubusercontent.com/16802605/141197603-6803b682-f06f-4990-ac88-e9c670ec2cab.mp4
