### ISSUE TITLE
Todo List 2

### ISSUE THREAD

**Issue by HaecheonLee** [HaecheonLee/maze#3]
* [x] Effect/Animation for each cell when visiting
* [x] Implenment Queue
* [x] queue.test.js
* [x] Implenment trace the path in bfs
* [x] Update dom property to data-*

**Comment by HaecheonLee** [comment]
https://user-images.githubusercontent.com/16802605/141608096-ff53ae6c-5986-4a5e-9cc6-e358ce38f53d.mp4

**Comment by HaecheonLee** [comment]
* path tracking using bfs

https://user-images.githubusercontent.com/16802605/141715307-66e1aa11-6c52-49e2-975d-994b6ae93663.mp4

**Comment by HaecheonLee** [comment]
Maybe enhancement for effect/animation when visiting?

**Comment by HaecheonLee** [comment]
* dfs visiting all node and come back

https://user-images.githubusercontent.com/16802605/141735448-3d23536d-d02d-4d65-a6e1-655aac945cbb.mp4
