### ISSUE TITLE
Todo List 3

### ISSUE THREAD

**Issue by HaecheonLee** [HaecheonLee/maze#4]
* [x] Buttons for visualization of DFS/BFS traversing
* [x] DFS from starting to ending
* [x] BFS from starting to ending

**Comment by HaecheonLee** [comment]
![12345](https://user-images.githubusercontent.com/16802605/142365613-32eff76c-1532-4a5b-b02d-6171315507fb.PNG)
