### ISSUE TITLE
Todo List 5

### ISSUE THREAD

**Issue by haecheonlee** [haecheonlee/maze#6]
* [x] Implement min-heap and its test unit
* [x] implement a* algorithm based on eucildean euclidean distance
* [x] Work on naming for functions and variables
* [ ] CSS/Animation for better visualization
* [ ] Enhance UI/UX
